### ISSUE TITLE
[Bug]: Windows Sandbox Fails to Start with an Error Code: 0x800705B4

### ISSUE THREAD

**Issue by CompactProducer** [microsoft/Windows-Sandbox-Utilities#101]
### Windows Sandbox version

0.5.3

### Windows build number

10.0.26200.7309

### Steps to reproduce the bug

1. Uninstall Windows Sandbox from Windows Features in Control Panel.
2. Reinstall Windows Sandbox from Windows Features in Control Panel.
3. Start Windows Sandbox.
4. Windows Sandbox will be updated to the latest version.
5. Windows Sandbox logo will stall with a spinning circle for ten minutes or so.
6. An error code will show: 0x800705B4.

### Expected result

Windows Sandbox is supposed to start after seeing a logo for three or five seconds.

### Actual result

Windows Sandbox logo will stall for ten minutes or so and an error code, 0x800705B4, will pop up. In C:\ProgramData\Microsoft\Windows\Containers\ContainerStorages, if I double-click a GUID (for example, ab243dfa-20dl-2k33-hjg8-2934hb767yh4), a sandbox.vhdx file will grow up to 1GB. After this, it gets deleted and Windows Sandbox exits with a 0x800705B4 error code.

**Comment by rolandambrosi** [comment]
This happen on Build 10.0.26200.7462 as well.

**Comment by CompactProducer** [comment]
> This happen on Build 10.0.26200.7462 as well.

I know. It did this on my PC as well. Wishing that Microsoft would release a patch to fix this problem.

**Comment by RenliGraphic** [comment]
Великолепное совпадение, а ведь именно сейчас мне и понадобился sandbox, когда он перестал работать.

**Comment by Rhadamantyszeroz** [comment]
The same steps and the same problem all updated, windows update, and microssoft store

win11 25h2 26200.7462

I hope build a pacth for resolve this issue

**Comment by CompactProducer** [comment]
> The same steps and the same problem all updated, windows update, and microssoft store
> 
> win11 25h2 26200.7462
> 
> I hope build a pacth for resolve this issue

This is what I'm hoping.

**Comment by Hakuin123** [comment]
same issue with win11 10.0.26220.7344
The version of Windows Sandbox is 0.5.3.0

**Comment by chocmake** [comment]
Experiencing same issue on W11 Pro 24H2 (build 26100.7462). Sandbox v0.5.3.0 (after reinstalling it, unsure what version it was prior).

Was stuck launching but unlike the OP no error message appeared. Then per a Microsoft Sandbox dev post on Reddit tried removing the feature, rebooting the system, reinstalling the feature, rebooting again, launching it (which showed an updated splash screen) and the 0x800705B4 error dialog appeared within ~5m.

**Comment by Marshyp** [comment]
We seem to be having the exact same issue. I've uninstalled and reinstalled and also tried resetting the app through settings to no joy. 
Interestingly, one of our users (on the same build) can run it with no issues, but most others fail with Error: 0x800705B4 - The operation timed out. 

Does anyone know if there are any work arounds or even any acknowledgements of this issue?

**Comment by CompactProducer** [comment]
> We seem to be having the exact same issue. I've uninstalled and reinstalled and also tried resetting the app through settings to no joy. Interestingly, one of our users (on the same build) can run it with no issues, but most others fail with Error: 0x800705B4 - The operation timed out.
> 
> Does anyone know if there are any work arounds or even any acknowledgements of this issue?

No workaround is available at this time; Microsoft may hopefully patch this issue in the near future.

**Comment by yaqwsx01** [comment]
I have the same problem. My Windows version is 26200.7462. In the Microsoft Store, the Sandbox version is 0.5.3.0.

**Comment by diegopego** [comment]
I have the same problem. Windows version is 26200.7462. In the Microsoft Store, the Sandbox version is 0.5.3.0.

**Comment by CompactProducer** [comment]
I've found a solution that fixes this problem:

1. Open Settings > System > Recovery.
2. Click **Reinstall now** if you see **Fix problems with Windows Update**.
3. Check the **Automatically restart my PC 15 minutes** and click **OK**.
4. Windows Update will check for updates, and then download and install a repair version of the latest Windows 11 version. After it completes, click **Restart now**.

After Windows Update repairs Windows 11, Windows Sandbox should start working again without showing an 0x800705B4 error code.

**Comment by Rhadamantyszeroz** [comment]
I think this not a factible soluction, I recreate your solution and works for the first reboot, but  when I restart the computer once again and open sandbox one more time the error come back....

And i Tried installing a fresh install of windows 11 and de first reboot installin de feature runs but when i rebbot de system the bug appear

We need a real fix not a reintall all Windows 11 via recovery....
I Think this,  but thanks for all

**Comment by Azadk** [comment]
I have a feeling this is caused by the latest NVIDIA driver update (591-44), which BTW is a mess :( 
The Issue happened to me after the installation of that driver and once I reverted back to the previous driver version, Sandbox started to work again. I upgraded to the newer driver (591-59) and now Sandbox is not working again.

**Comment by chocmake** [comment]
> I have a feeling this is caused by the latest NVIDIA driver update

In my case I'm on an older Nvidia version than either listed there and haven't updated the driver throughout this.

Sandbox had been working in mid October but since I only launched it again this month can't offer any finer timeline of when it broke.

**Comment by Rhadamantyszeroz** [comment]
I uninstall nvidia drivers and isntall varoius version and nothing work....
I used differents version with clear installation drivers

driver: 
581.80 
591.44
591.59
591.67 (hotfix released) 

And windows sandbox fails again with a sandbox.vhdx file will grow up to 1GB. After this, it gets deleted and Windows Sandbox exits with a 0x800705B4 error code.

For me nvidia installing old drivers not worksing on Windows 11 lastest version.

I hope Microsoft when Christsmas Holyday ends cointinue to works and make and update fixing the bug

**Comment by Rhadamantyszeroz** [comment]
I do a dump of process WindowsSandboxServer.exe that is de process generated de vdhx file for de sandbox and

always get same error 

SYMBOL_NAME:  coreclr!Thread::DoAppropriateWaitWorker+179

MODULE_NAME: coreclr

IMAGE_NAME:  coreclr.dll

FAILURE_BUCKET_ID:  BREAKPOINT_80000003_coreclr.dll!Thread::DoAppropriateWaitWorker

 Key  : Failure.Bucket
    Value: BREAKPOINT_80000003_coreclr.dll!Thread::DoAppropriateWaitWorker





**Here the dump info**

For analysis of this file, run !analyze -v

 Exception Analysis


*** WARNING: Unable to verify checksum for WindowsSandboxServer.dll
*** WARNING: Unable to verify checksum for WindowsSandboxServer.exe
ClrmaManagedAnalysis::GetThread 1850
ClrmaThread::Initialize 1850
~ClrmaThread
ClrmaManagedAnalysis::GetThread 43f8
ClrmaThread::Initialize 43f8
ClrmaThread::Initialize FAILED managed thread not found
~ClrmaThread
ClrmaManagedAnalysis::GetThread 44bc
ClrmaThread::Initialize 44bc
ClrmaThread::Initialize FAILED managed thread not found
~ClrmaThread
ClrmaManagedAnalysis::GetThread 085c
ClrmaThread::Initialize 085c
ClrmaThread::Initialize FAILED managed thread not found
~ClrmaThread
ClrmaManagedAnalysis::GetThread 4d04
ClrmaThread::Initialize 4d04
ClrmaThread::Initialize FAILED managed thread not found
~ClrmaThread
ClrmaManagedAnalysis::GetThread 1b38
ClrmaThread::Initialize 1b38
ClrmaThread::Initialize FAILED managed thread not found
~ClrmaThread
ClrmaManagedAnalysis::GetThread 3d70
ClrmaThread::Initialize 3d70
~ClrmaThread
ClrmaManagedAnalysis::GetThread 4538
ClrmaThread::Initialize 4538
~ClrmaThread
ClrmaManagedAnalysis::GetThread 1174
ClrmaThread::Initialize 1174
ClrmaThread::Initialize FAILED managed thread not found
~ClrmaThread
ClrmaManagedAnalysis::GetThread 087c
ClrmaThread::Initialize 087c
ClrmaThread::Initialize FAILED managed thread not found
~ClrmaThread
ClrmaManagedAnalysis::GetThread 2ac0
ClrmaThread::Initialize 2ac0
ClrmaThread::Initialize FAILED managed thread not found
~ClrmaThread
ClrmaThread::Initialize 1850
ClrmaThread::get_CurrentException
ClrmaThread::get_NestedExceptionCount
~ClrmaThread
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range


   Key  : CLR.Engine
 Value: CORECLR

Key  : CLR.Version
 Value: 8.0.1825.31117

 Key  : Failure.Bucket
Value: BREAKPOINT_80000003_coreclr.dll!Thread::DoAppropriateWaitWorker

Key  : Failure.Exception.Code
Value: 0x80000003

 Key  : Failure.Hash
Value: {2dbd2c7d-1f72-d894-343d-110a7c82a3a2}

 Key  : Failure.ProblemClass.Primary
 Value: BREAKPOINT

  Key  : Failure.Source.FileLine
 Value: 3467

Key  : Failure.Source.FilePath
  Value: D:\a\_work\1\s\src\coreclr\vm\threads.cpp

 Key  : Failure.Source.SourceServerCommand
 Value: raw.githubusercontent.com/dotnet/runtime/ef853a71052646a42abf17e888ec6d9a69614ad9/src/coreclr/vm/threads.cpp


FILE_IN_CAB:  WindowsSandboxServer.dmp

NTGLOBALFLAG:  0

APPLICATION_VERIFIER_FLAGS:  0

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 0000000000000000
   ExceptionCode: 80000003 (Break instruction exception)
  ExceptionFlags: 00000000
NumberParameters: 0

FAULTING_THREAD:  1850

PROCESS_NAME:  WindowsSandboxServer.dll

ERROR_CODE: (NTSTATUS) 0x80000003 - {EXCEPCI N}  Punto de interrupci n  Se ha alcanzado un punto de interrupci n.

EXCEPTION_CODE_STR:  80000003

STACK_TEXT:  
000000a2`ec97ddf8 00007ffc`79cedf83     : 00000000`00000000 00007ffb`c00e30b8 000001ed`9ae651d0 000001ed`9a1228b0 : ntdll!NtWaitForMultipleObjects+0x14
000000a2`ec97de00 00007ffc`1f136365     : 00000000`00000000 00007ffb`c047f478 00000000`00000001 000001ed`9a172140 : KERNELBASE!WaitForMultipleObjectsEx+0x123
(Inline Function) --------`--------     : --------`-------- --------`-------- --------`-------- --------`-------- : coreclr!Thread::DoAppropriateAptStateWait+0x45
000000a2`ec97e0f0 00007ffc`1f1361aa     : 00007ffc`00000001 000001ed`00000001 00000000`00000001 00007ffc`00000000 : coreclr!Thread::DoAppropriateWaitWorker+0x179
000000a2`ec97e1b0 00007ffc`1f1353c8     : 00000000`00000000 00000000`00000001 00000000`00000000 00007ffb`c02f2688 : coreclr!Thread::DoAppropriateWait+0x82
(Inline Function) --------`--------     : --------`-------- --------`-------- --------`-------- --------`-------- : coreclr!CLREventBase::WaitEx+0x3e
(Inline Function) --------`--------     : --------`-------- --------`-------- --------`-------- --------`-------- : coreclr!CLREventBase::Wait+0x49
(Inline Function) --------`--------     : --------`-------- --------`-------- --------`-------- --------`-------- : coreclr!Thread::Wait+0x49
(Inline Function) --------`--------     : --------`-------- --------`-------- --------`-------- --------`-------- : coreclr!Thread::Block+0x51
000000a2`ec97e230 00007ffc`1f1344cd     : 00000000`00000000 00007ffc`ffffffff 000001ed`9f133518 000001ed`9a11e390 : coreclr!SyncBlock::Wait+0x1d4
(Inline Function) --------`--------     : --------`-------- --------`-------- --------`-------- --------`-------- : coreclr!ObjHeader::Wait+0x42
(Inline Function) --------`--------     : --------`-------- --------`-------- --------`-------- --------`-------- : coreclr!Object::Wait+0x42
000000a2`ec97e350 00007ffc`1e6dd8ee     : 000000a2`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : coreclr!ObjectNative::WaitTimeout+0xcd
000000a2`ec97e4d0 00007ffc`1e6e899e     : 000001ed`9f1334f0 00000000`00000001 00000000`0007ffff 000001ed`9f1334f0 : System_Private_CoreLib!System.Threading.Monitor.Wait+0x1e
000000a2`ec97e500 00007ffc`1e701c00     : 000001ed`9f1334f0 00000000`ffffffff 00000000`00000000 00000000`0000000a : System_Private_CoreLib!System.Threading.ManualResetEventSlim.Wait+0x1be
000000a2`ec97e5a0 00007ffc`1e7019d6     : 000001ed`9f133488 00000000`ffffffff 00000000`00000000 000001ed`9f133488 : System_Private_CoreLib!System.Threading.Tasks.Task.SpinThenBlockingWait+0xc0
000000a2`ec97e620 00007ffc`1e753a05     : 000001ed`9f133488 00000000`ffffffff 00000000`00000000 000001ed`9f133488 : System_Private_CoreLib!System.Threading.Tasks.Task.InternalWaitCore+0x76
000000a2`ec97e6a0 00007ffc`1e85c760     : 000001ed`9f133488 00000000`00000000 00000000`00000000 000001ed`9f133488 : System_Private_CoreLib!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification+0x25
000000a2`ec97e6e0 00007ffb`bf65247f     : 000000a2`ec97e738 000001ed`9f018a08 00000000`00000000 000001ed`9f133488 : System_Private_CoreLib!System.Runtime.CompilerServices.TaskAwaiter<int>.GetResult+0x30
000000a2`ec97e710 000000a2`ec97e738     : 000001ed`9f018a08 00000000`00000000 000001ed`9f133488 00000000`00000004 : WindowsSandboxServer!SandboxServer.Program.<Main>+0x2f
000000a2`ec97e718 000001ed`9f018a08     : 00000000`00000000 000001ed`9f133488 00000000`00000004 000001ed`9f133488 : 0x000000a2`ec97e738
000000a2`ec97e720 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : 0x000001ed`9f018a08


STACK_COMMAND: ~0s; .ecxr ; kb

FAULTING_SOURCE_LINE:  D:\a\_work\1\s\src\coreclr\vm\threads.cpp

FAULTING_SOURCE_FILE:  D:\a\_work\1\s\src\coreclr\vm\threads.cpp

FAULTING_SOURCE_LINE_NUMBER:  3467

FAULTING_SOURCE_SRV_COMMAND:  https://raw.githubusercontent.com/dotnet/runtime/ef853a71052646a42abf17e888ec6d9a69614ad9/src/coreclr/vm/threads.cpp

FAULTING_SOURCE_CODE:  
No source found for 'D:\a\_work\1\s\src\coreclr\vm\threads.cpp'


SYMBOL_NAME:  coreclr!Thread::DoAppropriateWaitWorker+179

MODULE_NAME: coreclr

IMAGE_NAME:  coreclr.dll

FAILURE_BUCKET_ID:  BREAKPOINT_80000003_coreclr.dll!Thread::DoAppropriateWaitWorker

OS_VERSION:  10.0.26100.1

BUILDLAB_STR:  ge_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

IMAGE_VERSION:  8.0.1825.31117

FAILURE_ID_HASH:  {2dbd2c7d-1f72-d894-343d-110a7c82a3a2}

Followup:     MachineOwner
---------

CLRMAReleaseInstance
~ClrmaManagedAnalysislysis

**Comment by JustAT0rtoise** [comment]
Have you guys tried running Windows Sandbox as Administrator?

I have:
- Windows Sandbox 0.5.3.0
- Windows 25H2 (Build 26200.7462)
- AMD GPU

And it works for me when I "Run as administrator."

**Comment by Rhadamantyszeroz** [comment]
Yes I tried and not work i have nvidia graphics card rtx and intel chipset z790 drivers updated and bios and nothing

I tried also repair de Net frame work 8.0 and still the bug appear

and i tried to create a wsb file with .VGpu disable /VGpu. and nothing  < > removed for this post

I think that 12/12 before this date the sandbox works fine but after that date in my case stop working....

Still I unistalll de last kb of december but the same result..... (first to unistall this kb i have to tun off the feature, unnistall de kb restart and after install de feature but the same bug)

Even I tried to back the date of the os but the same bug

Windows Sandbox 0.5.3.0
Windows 25H2 (Build 26200.7462)
nvidia rtx 3060
chipset intel z790

All drivers updated and last bios
All app update via winget and mstore
sfc, dsim and chkdsk no errors found

Thanks for information

I can get and error visible into event viewer

Nombre de aplicación con errores: WindowsSandboxRemoteSession.exe, versión: 0.5.3.0, marca de tiempo: 0x684a0000
Nombre del módulo con errores: coreclr.dll, versión: 8.0.1825.31117, marca de tiempo: 0x684a1ad1
Código de excepción: 0xc0000005
Desplazamiento con errores: 0x00000000003b801e
Id. de proceso con errores: 0x3724
Tiempo de inicio de aplicación con errores: 0x1DC76931061CD50
Ruta de aplicación con errores: C:\Program Files\WindowsApps\MicrosoftWindows.WindowsSandbox_0.5.3.0_x64__cw5n1h2txyewy\WindowsSandboxRemoteSession.exe
Ruta de módulo con errores: C:\Program Files\WindowsApps\MicrosoftWindows.WindowsSandbox_0.5.3.0_x64__cw5n1h2txyewy\coreclr.dll
Id. de informe: 1ef80eb0-0986-488f-a270-aadcbed1b8d5
Nombre completo del paquete con errores: MicrosoftWindows.WindowsSandbox_0.5.3.0_x64__cw5n1h2txyewy
Id. de aplicación relacionado con el paquete con errores: App


Thats indicate that the other post with then dump sais the same dll is problematic o have and error with windows sandbox coreclr.dll

or when execute de windows sandbox its have waiting for other subprocess hya have use remon and monitoring the process and then wait to crash and I have this image and the error on eventy viewer

<img width="730" height="570" alt="Image" src="https://github.com/user-attachments/assets/da2854b7-b2c9-4219-b6d3-97c0ce53cd26" />

So I think the trouble is on .net framework 8.0 or excutable for windos sandbox or a combined error with the last kb for os windows

**Comment by gabriel-vanca** [comment]
Can confirm 26220.7523 also has this issue.
Running as Administrator doesn't help, nor does reinstalling. Tried SFC, DSIM  to no avail.
AMD CPU and Nvidia GPU.

**Comment by kranorzor** [comment]
I have exactly this error with the latest Windows 11 - 25H2 26200.7462
With latest Sandbox version 0.5.3.0 - dated 09/11/2025 from microsoft store.
I've done everything posted in this thread and more but nothing worked as workround or a fix at all, using a normal VM via hyper-V now but it's not the same (security) etc
I really hope that they fix this and fast because i use that at work and at home a lot, and it's the kind of thing to fix from one day to another.

**Comment by qqqle123co** [comment]
I'm having the same problem.
I've already done everything I should, but this error won't go away.
I'll try other methods, but I really want them to fix this, as this bug has been around for a long time.

**Comment by Benjam1nIT** [comment]
Same problem, Windows 11 24h2, 26100.7462, I uninstalled + reinstalled the Sandbox feature (took forever) and the problem remains.

**Comment by rebel2k** [comment]
Same problem as others, since a couple of updates in the 25H2 branch. Splashscreen, loads forever, and after a long time display the same error 0x800705B4. It's not working anymore for several weeks now... Would have been nice to get some visibility on what is wrong and when it's planned to release a fix for that. It's annoying that feature has been broken at least 3 times in 2025 because of updates...

**Comment by calimegot** [comment]
> Have you guys tried running Windows Sandbox as Administrator?
> 
> I have:
> 
> * Windows Sandbox 0.5.3.0
> * Windows 25H2 (Build 26200.7462)
> * AMD GPU
> 
> And it works for me when I "Run as administrator."

I tried , but same issue for me... 
Stuck on the circle for long time.
Win 11 25H2 and last version for sandbox

**Comment by calimegot** [comment]
WTF... i can't use Sandbox for my job and i need it next monday.
I'll use Hyper-V and waiting for a fix

**Comment by ergo1945** [comment]
I have one laptop and one desktop computer. Both are running Windows 11 25H2 Build 26200.7462. The desktop meets the requirements for Windows 11, but the laptop does not. I had to install Windows 11 on the laptop using 'Rufus'. I'm experiencing the same problems with the sandbox on the desktop, but the Sandbox runs flawlessly on the laptop. Perhaps this information will help identify the problem.
(I used the Google translater).

**Comment by kranorzor** [comment]
> WTF... i can't use Sandbox for my job and i need it next monday. I'll use Hyper-V and waiting for a fix

Same for me mate, ok the holidays, but this is a critical bug a fix it would have been right to release ASAP.
It's 1 month now.

**Comment by Tommyhasabird** [comment]
Same on Windows 11 26200.7462, Windows Sandbox 0.5.3.0 with Intel(R) Core(TM) Ultra 9 185H and Arc graphics. Worked before a update.

**Comment by Tommyhasabird** [comment]
When the application starts, there is a intense lag, don't know if anyone has this problem too.

**Comment by kranorzor** [comment]
> When the application starts, there is a intense lag, don't know if anyone has this problem too.

Yes it's common to have some lag for some time don't worry.

**Comment by viktorklim47-sketch** [comment]
Something strange is happening. 
I have two laptops with Windows 11 Pro 25H2 (26200.7462).
One has an Intel Core i5-8365U processor and Intel UHD 620 graphics. Sandbox works without problems.
The other has an AMD Ryzen 7 5700 processor and AMD Radeon graphics. Sandbox doesn't work — it gives the same error 0x800705B4.

**Comment by viktorklim47-sketch** [comment]
I forgot to mention. One laptop has English Windows, and the other one has Russian. Guess which one works correctly  :-).

**Comment by Machou** [comment]
Same on Windows 11 26200.7462, Windows Sandbox 0.5.3.0 with Intel(R) Core(TM) i7-14700K.

I have try i with:

- Nvidia drivers **591.44** and **591.74**
- with and without Hyper-V


and

```
Dism /Online /Cleanup-Image /ScanHealth
Dism /Online /Cleanup-Image /CheckHealth
Dism /Online /Cleanup-Image /RestoreHealth
SFC /SCANNOW
```

Worked before a update.

**Comment by xiaoqidun** [comment]
Windows 11 专业工作站版 26200.7462（Windows 功能体验包 1000.26100.275.0）同样问题

**Comment by cbesot** [comment]
Same here. I tried all kind of things like uninstall/reinstall
dism /online /enable-feature /featurename:Microsoft-Hyper-V-All /all /norestart
dism /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
dism /online /enable-feature /featurename:Windows-Hypervisor-Platform /all /norestart
dism /online /enable-feature /featurename:Containers /all /norestart
dism /online /enable-feature /featurename:Containers-DisposableClientVM /all /norestart

or desactivate GPU
reg add "HKLM\SOFTWARE\Microsoft\Windows Sandbox" /v DisableGpuAcceleration /t REG_DWORD /d 1 /f

Nothing works.

**Comment by martin-konkol** [comment]
This happens to me too. Sandbox used to work perfectly, now does not work at all, producing the above mentioned error. Windows 11 fully patched. Nvidia RTX4080 tested with several gpu driver versions (none work anymore). I've tried all kinds of repairs through dism and sfc. Updated all drivers and motherboard BIOS to latest version even. Nothing helps. Reinstalls of Windows Sandbox and/or Virtual Machine Platform or Hyper-V do not help.

From what I'm reading on reddit and elsewhere on the internet, this seems to be progressively spreading faster and faster to just about everyone. Can we get some reaction? At least a confirmation that this is being looked into?

**Comment by bernox89** [comment]
Same problem with Windows 25H2

**Comment by rebel2k** [comment]
So, I had some time to investigate this a little deeper.

### Summary
After installing KB5070311 (or maybe a previous patch) on Windows 11 Insider (Release Preview, build 26200.7462), Windows Sandbox no longer starts and fails with 0x800705B4 (timeout).

### Root cause
Sandbox launches vmcompute and vmwp successfully, but never enters the Containers provisioning path. No container image resolution or storage access is attempted.

### Notes
- Hyper‑V and WSL continue to work normally.
- Required features and services are enabled and running.
- Reinstalling the Sandbox feature does not recreate the BaseImages directory.
- **Sandbox launches vmcompute and vmwp successfully, but never enters the Containers provisioning path. No container image resolution or storage access is attempted. This appears to be a regression in Sandbox scenario activation rather than a missing image or configuration issue.**

### Impact
Windows Sandbox is completely unusable on affected systems.

### Suspected regression
Provisioning of Windows Sandbox base images appears broken starting with KB5070311 (or maybe a previous one).

**Comment by rebel2k** [comment]
A little more technical details now that I could grab a whole trace with ProcMon:

### 1. Hyper-V Infrastructure Healthy:
   - vmms.exe (PID 4048) and vmcompute.exe (PID 4356) successfully create/load VM config files (.vmcx), mappings for C32.dll/exe.
   - All FileSystemControl, CreateFileMapping, QuerySecurityFile operations on system files (32.dll, .sdb) return SUCCESS.
   - No ACCESS_DENIED, STATUS_FILE_LOCKED, or I/O timeouts in early VM setup phase.

### 2. Sandbox VHDX Creation & Growth:
   - Sandbox VHDX: C67c5896-3699-4e6f-9b26-5cb6aa5dd754.vhdx (for the run I traced down).
   - Phase 1 (Sysprep): vmmemCmSysprep (PID 74012) writes continuously ~295MB+ offsets, 4-65KB blocks, all SUCCESS non-cached IO.
   - Phase 2 (FirstBoot): Transitions to vmmemCmFirstBoot (PID 53304), reads/writes high offsets (341MB+, up to 820MB+), indicating guest OS OOBE/config in progress.
   - VHDX grows as expected during boot sequence, no disk/NTFS errors.

### 3. Failure Pattern:
   - No explicit errors (IRP_MJ_DEVICE_CONTROL, DeviceIoControl failures) explaining timeout.
   - Activity continues post-Sysprep into FirstBoot, but Sandbox UI times out (likely 0x800705B4) waiting for guest readiness signal.
   - Container orchestration fails handshake despite VM I/O healthy.

### Environment:
- Windows 11 25H2 Build 26200.7462
- Windows Sandbox 0.5.13 (Microsoft Store, 2025-09-11)
- Hyper-V features enabled, no WSL/VMware conflicts visible.

**Implication: Product bug in Sandbox boot orchestration, not host storage/Hyper-V fault.**

**Comment by Rhadamantyszeroz** [comment]
> So, I had some time to investigate this a little deeper.
> 
> ### Summary
> After installing KB5070311 (or maybe a previous patch) on Windows 11 Insider (Release Preview, build 26200.7462), Windows Sandbox no longer starts and fails with 0x800705B4 (timeout).
> 
> ### Root cause
> The directory _C:\ProgramData\Microsoft\Windows\Containers\BaseImages_ is empty after the update. Sandbox cannot initialize without a base image and hangs until timeout.
> 
> ### Notes
> * Hyper‑V and WSL continue to work normally.
> * Required features and services are enabled and running.
> * Reinstalling the Sandbox feature does not recreate the BaseImages directory.
> * **Sandbox launches vmcompute and vmwp successfully, but never enters the Containers provisioning path. No container image resolution or storage access is attempted. This appears to be a regression in Sandbox scenario activation rather than a missing image or configuration issue.**
> 
> ### Impact
> Windows Sandbox is completely unusable on affected systems.
> 
> ### Suspected regression
> Provisioning of Windows Sandbox base images appears broken starting with KB5070311 (or maybe a previous one).

Its a great explantion that whats happened here
Thanks a lot for this

**Comment by vb87** [comment]
This is probably AMD Ryzen related, virtualization seems lot more finicky for AMD, and AMD Ryzen line and gets broken more often

I'm on Windows 11 version 25H2 (OS Build 26200.7462)
AMD Ryzen 7 Mobile 3750H, 24GB RAM, GTX 1660 TI, running on SSD, virtualization enabled in BIOS, hyper-v etc. all correct as when worked before
Tried reinstalling sandbox, tried starting without vgpu, tried several other things, nothing works. In previous builds sandbox worked without issue.

**Comment by VektreX** [comment]
> This is probably AMD Ryzen related, virtualization seems lot more finicky for AMD, and AMD Ryzen line and gets broken more often
> 
> I'm on Windows 11 version 25H2 (OS Build 26200.7462) AMD Ryzen 7 Mobile 3750H, 24GB RAM, GTX 1660 TI, running on SSD, virtualization enabled in BIOS, hyper-v etc. all correct as when worked before Tried reinstalling sandbox, tried starting without vgpu, tried several other things, nothing works. In previous builds sandbox worked without issue.

Probably not, I am using an Intel CPU (8086K) and I have the issue as well.

**Comment by rebel2k** [comment]
> This is probably AMD Ryzen related, virtualization seems lot more finicky for AMD, and AMD Ryzen line and gets broken more often

It's not AMD related, no. I'm also using Intel as plenty of other affected users. It needs an update of the sandbox app but I'm not even sure Microsoft is reading anything here... (repo hasn't been touched in ages)

**Comment by xiaoqidun** [comment]
> This is probably AMD Ryzen related, virtualization seems lot more finicky for AMD, and AMD Ryzen line and gets broken more often
> 
> I'm on Windows 11 version 25H2 (OS Build 26200.7462) AMD Ryzen 7 Mobile 3750H, 24GB RAM, GTX 1660 TI, running on SSD, virtualization enabled in BIOS, hyper-v etc. all correct as when worked before Tried reinstalling sandbox, tried starting without vgpu, tried several other things, nothing works. In previous builds sandbox worked without issue.

This isn't an AMD-specific issue; the Intel 275HX + 5080 combo has the exact same problem.

**Comment by Rhadamantyszeroz** [comment]
Here  also there all people that have same problem

https://learn.microsoft.com/en-us/answers/questions/5647136/windows-sandbox-fails-to-open-with-0x800705b4?page=4&orderby=Helpful&translated=false

I hope posting here and there Microsoft release a hotfix, new version, fix or else and that they pay attention to us.

**Comment by Rhadamantyszeroz** [comment]
Windows 11 pro jan 2016 update installed, the bug still here....

Win11 25h2 26200.7623

**Comment by wickedaverage** [comment]
> ### Root cause
> The directory _C:\ProgramData\Microsoft\Windows\Containers\BaseImages_ is empty after the update. Sandbox cannot initialize without a base image and hangs until timeout.

I don't think this part is accurate. I have 2 machines and the problem exists on 1 of my 2 machines. On BOTH machines, the directory is empty. Hyper-V and WSL works on both, it is literally just Sandbox that is broken on 1 of them.

Machine 1 (Sandbox working) - Surface Pro 8 Laptop
- Host CPU 11th gen Intel i7 1185G7
Windows 11 Pro 25H2 26200.7623

Machine 2 (Sandbox not working) - Win 11 Guest VM (Proxmox hypervisor - GPU passthrough, Host CPU type)
- Host CPU AMD Ryzen 3950X > this is what the VM sees
Windows 11 Pro 25H2 26200.7462

I have had issues getting Sandbox working over the years in my VM with nested virtualization (i.e. Sandbox, Hyper-V, WSL) etc, but recently it had been working fine. After the updates mentioned in this thread, Sandbox stopped working but Hyper-V, WSL etc continue to work.

**Comment by buchizo** [comment]
In my case, after installing KB5074109 in today's Windows Update and updating Windows to 26200.7623, Windows Sandbox started working again. (I've only tested it on one computer so far.)

I don't know what caused it to work.

**Comment by KHeresy** [comment]
It still not work in my computer after install KB5074109.

I had tried to remove and reinstall sandbox, not help.

**Comment by xiaoqidun** [comment]
The problem persists even after updating KB5074109 26200.7623.

**Comment by rebel2k** [comment]
> > ### Root cause
> > The directory _C:\ProgramData\Microsoft\Windows\Containers\BaseImages_ is empty after the update. Sandbox cannot initialize without a base image and hangs until timeout.
> 
> I don't think this part is accurate. I have 2 machines and the problem exists on 1 of my 2 machines. On BOTH machines, the directory is empty. Hyper-V and WSL works on both, it is literally just Sandbox that is broken on 1 of them.

You're totally right! That's something I started to write initially in my investigations but forgot to modify at the end and only changed in my "notes" below. I'll do it now! :)

**Comment by calimegot** [comment]
As i can see, Sandbox won't work, and for me WSA too...
I can't use any Android app...

**Comment by rebel2k** [comment]
On my side, new update KB5074109 (26200.7623) and problem is still there... :(

Quick questions for you around: how many directories do you have in C:\ProgramData\Microsoft\Windows\Containers\Layers? (I have 3 on my computer, and one which has been created today, when the patch KB5074109 got installed).

**Comment by x8009** [comment]
same issue with newest update just released yesterday 25h2

**Comment by oreactko** [comment]
same issue with newest preview update 26h1

**Comment by oreactko** [comment]
> A little more technical details now that I could grab a whole trace with ProcMon:
> ### 1. Hyper-V Infrastructure Healthy:
> 
>     * vmms.exe (PID 4048) and vmcompute.exe (PID 4356) successfully create/load VM config files (.vmcx), mappings for C32.dll/exe.
> 
>     * All FileSystemControl, CreateFileMapping, QuerySecurityFile operations on system files (32.dll, .sdb) return SUCCESS.
> 
>     * No ACCESS_DENIED, STATUS_FILE_LOCKED, or I/O timeouts in early VM setup phase.
> 
> 
> ### 2. Sandbox VHDX Creation & Growth:
> 
>     * Sandbox VHDX: C67c5896-3699-4e6f-9b26-5cb6aa5dd754.vhdx (for the run I traced down).
> 
>     * Phase 1 (Sysprep): vmmemCmSysprep (PID 74012) writes continuously ~295MB+ offsets, 4-65KB blocks, all SUCCESS non-cached IO.
> 
>     * Phase 2 (FirstBoot): Transitions to vmmemCmFirstBoot (PID 53304), reads/writes high offsets (341MB+, up to 820MB+), indicating guest OS OOBE/config in progress.
> 
>     * VHDX grows as expected during boot sequence, no disk/NTFS errors.
> 
> 
> ### 3. Failure Pattern:
> 
>     * No explicit errors (IRP_MJ_DEVICE_CONTROL, DeviceIoControl failures) explaining timeout.
> 
>     * Activity continues post-Sysprep into FirstBoot, but Sandbox UI times out (likely 0x800705B4) waiting for guest readiness signal.
> 
>     * Container orchestration fails handshake despite VM I/O healthy.
> 
> 
> ### Environment:
> 
>     * Windows 11 25H2 Build 26200.7462
> 
>     * Windows Sandbox 0.5.13 (Microsoft Store, 2025-09-11)
> 
>     * Hyper-V features enabled, no WSL/VMware conflicts visible.
> 
> 
> **Implication: Product bug in Sandbox boot orchestration, not host storage/Hyper-V fault.**

yeah, when I tried run Hyper-V VM, it was ok

**Comment by chocmake** [comment]
> Quick questions for you around: how many directories do you have in C:\ProgramData\Microsoft\Windows\Containers\Layers? (I have 3 on my computer, and one which has been created today, when the patch KB5074109 got installed).

I have two, following the KB5074109 update (unsure how many were there prior). In one the root `dotnet.bcf` file is dated yesterday (when I installed the update) and in the other mid December (aligns with my first post in this topic).

**Comment by vb87** [comment]
> > ### Root cause
> > The directory _C:\ProgramData\Microsoft\Windows\Containers\BaseImages_ is empty after the update. Sandbox cannot initialize without a base image and hangs until timeout.
> 
> I don't think this part is accurate. I have 2 machines and the problem exists on 1 of my 2 machines. On BOTH machines, the directory is empty. Hyper-V and WSL works on both, it is literally just Sandbox that is broken on 1 of them.
> 
> Machine 1 (Sandbox working) - Surface Pro 8 Laptop
> 
> * Host CPU 11th gen Intel i7 1185G7
>   Windows 11 Pro 25H2 26200.7623
> 
> Machine 2 (Sandbox not working) - Win 11 Guest VM (Proxmox hypervisor - GPU passthrough, Host CPU type)
> 
> * Host CPU AMD Ryzen 3950X > this is what the VM sees
>   Windows 11 Pro 25H2 26200.7462
> 
> I have had issues getting Sandbox working over the years in my VM with nested virtualization (i.e. Sandbox, Hyper-V, WSL) etc, but recently it had been working fine. After the updates mentioned in this thread, Sandbox stopped working but Hyper-V, WSL etc continue to work.


notice that your second machine that's not working is AMD Ryzen, I've seen how on so many setups AMD Ryzen is so much more finicky with virtualization, although one use reported that on his Intel CPU machine sandbox is broken too, it could be there are two issues, or the user had unrelated issue, or perhaps it's issue that mainly hits AMD Ryzen line and some select non-AMD CPUs

someone over at Microsoft should test sandbox on AMD Ryzen CPU machines, they are very common CPUs nowadays

**Comment by Cotangent0424** [comment]
I notice that every time I try to start Windows Sandbox, Device Manager creates a hidden device called "Microsoft Virtual Disk," and it is in a disconnected state. I remember that when it was working before, this device didn't appear.

I think I modified the Hyper-V virtual machine and virtual hard disk locations, and after that, it stopped opening. Can you modify the sandbox settings to point to the new location? I'm not sure if it’s because I changed the Hyper-V virtual disk and virtual machine locations that caused it to fail to open.

Windows Sandbox failed to initialize.  
The operation returned because the timeout period expired. (0x800705B4)

I have changed the settings back now, so why is it still not working?

I noticed that there is no content to display in the virtual disk, and the "Microsoft Virtual Disk" in Device Manager remains in a disconnected state.  
C:\ProgramData\Microsoft\Windows\Containers\ContainerStorages\………………  
Every time I start Windows Sandbox, files appear in this container folder, and after the sandbox reports an error and fails to open, the files disappear.

This is my desired Hyper-V configuration path:

Get-VMHost | Select-Object VirtualMachinePath, VirtualHardDiskPath

VirtualMachinePath                                        VirtualHardDiskPath
------------------                                        -------------------
C:\ProgramData\Microsoft\Windows\Hyper-V\Virtual Machines C:\ProgramData\Microsoft\Windows\Virtual Hard Disks

**Comment by CompactProducer** [comment]
> On my side, new update KB5074109 (26200.7623) and problem is still there... :(
> 
> Quick questions for you around: how many directories do you have in C:\ProgramData\Microsoft\Windows\Containers\Layers? (I have 3 on my computer, and one which has been created today, when the patch KB5074109 got installed).

I have two on my PC, so having three or more shouldn't do any harm. Windows Sandbox may use a newer folder after Windows gets updated. For example:
<img width="532" height="218" alt="Image" src="https://github.com/user-attachments/assets/c1c97651-ac4c-4c92-8dca-1e02704b934a" />
A folder that's been modified on 24/12/2025 is an outdated layer, so Windows Sandbox will use a folder that's been modified on 13/01/2026 and an updated layer.

**Comment by justid** [comment]
After a month ,this bug is still not fixed on 25H2 build 26200.7623

**Comment by michaelhetzer90-design** [comment]
Ich hoffe die wissen das es einen Fehler gibt und daran arbeiten !!

**Comment by x2605** [comment]
I have same issue.
There are few information about my computer and few event viewer log.
[event_viewer_report.xml](https://github.com/user-attachments/files/24700015/event_viewer_report.xml)
[system_info(ko).txt](https://github.com/user-attachments/files/24700014/system_info.ko.txt)

**Comment by Seikilos** [comment]
Same issue.
This is my system when starting sandbox

<img width="748" height="518" alt="Image" src="https://github.com/user-attachments/assets/feee17cd-9203-44da-bce5-ccf575cf3599" />
vmmemCmFirstBoot is going nuts.

**Comment by rebel2k** [comment]
> Same issue. This is my system when starting sandbox
> 
> <img alt="Image" width="748" height="518" src="https://private-user-images.githubusercontent.com/1260908/537683080-feee17cd-9203-44da-bce5-ccf575cf3599.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njg4NDI2OTMsIm5iZiI6MTc2ODg0MjM5MywicGF0aCI6Ii8xMjYwOTA4LzUzNzY4MzA4MC1mZWVlMTdjZC05MjAzLTQ0ZGEtYmNlNS1jY2Y1NzVjZjM1OTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjAxMTlUMTcwNjMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODM1ODUwOTdjNGQyZWJhZWI3OTlhMTdjZjI2YzM1NjNjNDk0ZjNkMDc2OWZkM2Q5ZTY5ZTkyODYyZDY4MmRiNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.9I6ZCsu7Md2GvB2RqG_AIHcRwtlimc6wq14X5JJcpdU"> vmmemCmFirstBoot is going nuts.

Going nuts for nothing as it doesn't even start at the end of the day... :(

**Comment by jv902337** [comment]
When I have run the sandbox via admin without any WSB file it has created an ETL file that can be read by perfview.  The location is 
C:\Windows\Logs\Containers\ContainerTraceUser.etl
I have not been able to find anything yet but thought I would post it here and see if others could take a crack at it

**Comment by rebel2k** [comment]
Oh good spot. I need to check on my system. Do you mind sharing it?

**Comment by Seikilos** [comment]
It is always 0 bytes for me

**Comment by dcavni** [comment]
Broken on my computer. 

This operation returned because the timeout period expired. (0x800705B4)

25H2   26200.7623

**Comment by edcba1057344** [comment]
The same problem is happening in Korea

Windows 11 Pro
24H2
OS Build 26100.7623
Experience Windows Feature Experience Pack 1000.26100.275.0


It's my computer's specification


AMD Ryzen 7 9800X3D
RAM 96.0GB
NVIDIA GeForec RTX 5080


I hope this will be resolved

**Comment by rhinterndorfer** [comment]
Same problem here. The Event Viewer logged an event of a success booted OS on 24.01.2026 10:48 and 10 minutes later the same machine was turned off. That corresponds to the time I have waited for the sandbox to start.

<img width="2458" height="1604" alt="Image" src="https://github.com/user-attachments/assets/1d03dace-e45a-4e51-bacf-e4d941fc5700" />

**Comment by latiao-1337** [comment]
The same problem

**Comment by xiaoqidun** [comment]
The problem persists even after updating KB5078127 26200.7628.

**Comment by x8009** [comment]
I had to uninstall sandbox it killed my CPU usage . like was in a loop.  as soon as I want to start using it .. it decide it's fak up. freaking Microsoft Nvidia And every time

**Comment by Rhadamantyszeroz** [comment]
Windows 11 25h2 26200.7628
The bug still here Windows sandbox same error....

**Comment by rebel2k** [comment]
Agreed, still doesn't work with 26200.7628.

**Comment by Unrepentant-Atheist** [comment]
It works if you do a complete fresh OS install/reinstall. But that's not a solution.

**Comment by rebel2k** [comment]
> It works if you do a complete fresh OS install/reinstall. But that's not a solution.

I actually did a full "fix/reinstall" on top of the existing installation (using the recovery option) and it didn't make it work.
(but you're 100% right anyway, if that works in some cases, that's not a solution)

**Comment by Machou** [comment]
Try with [WSL 2.7.7](https://github.com/microsoft/WSL/releases/tag/2.7.0)

and : [2026-01 Correctif (KB5078127) (26200.7628)](https://support.microsoft.com/en-us/topic/january-24-2026-kb5078127-os-builds-26200-7628-and-26100-7628-out-of-band-cf5777f6-bb4e-4adb-b9cd-2b64df577491)

Nope :(

**Comment by CompactProducer** [comment]
> It works if you do a complete fresh OS install/reinstall. But that's not a solution.

It MAY be a good idea, but not a solution can work for everyone. Plus, don't think that Windows Sandbox may work straight away after a fresh Windows reinstallation, so see if it does after that.

**Comment by vitorsr** [comment]
Does not work after a fresh install.

**Comment by michaelhetzer90-design** [comment]
> Versuche es mit [WSL 2.7.7](https://github.com/microsoft/WSL/releases/tag/2.7.0)
> 
> und: [2026-01 Korrektur (KB5078127) (26200,7628)](https://support.microsoft.com/en-us/topic/january-24-2026-kb5078127-os-builds-26200-7628-and-26100-7628-out-of-band-cf5777f6-bb4e-4adb-b9cd-2b64df577491)
> 
> Nein, :(

Es funktioniert auch nicht nach dem Update KB5078127 !!

**Comment by CompactProducer** [comment]
Has anyone sent feedbacks to Microsoft about Windows Sandbox's error code 0x800705B4 by using Feedback Hub? If you've not, I suggest that you start sending feedbacks.

**Comment by rebel2k** [comment]
> Has anyone sent feedbacks to Microsoft about Windows Sandbox's error code 0x800705B4 by using Feedback Hub? If you've not, I suggest that you start sending feedbacks.

We did. Plenty. There are TONS of feedback opened for that very same issue. Nobody cares. At all.

EDIT: well, after I contacted someone working at Microsoft during the past weekend, it looks like the status of those feedbacks have changed to "we're working on it"... Let's see what happens in the coming weeks!

**Comment by rhinterndorfer** [comment]
Does work in Windows 11 Pro 26200.7171 and does not work in Windows 11 Pro 26200.7623 (same machine):
<img width="1280" height="759" alt="Image" src="https://github.com/user-attachments/assets/21f1dcd9-b9aa-45bf-8e10-6631dfa1b63e" />

<img width="1280" height="763" alt="Image" src="https://github.com/user-attachments/assets/557d57c8-a789-49fc-ab7e-455ada0da058" />

**Comment by ergo1945** [comment]
When you install Windows 11 Build 26200.7628 **with Rufus** the sandbox works., even on Computers which dosn't match with Windows 11

**Comment by x8009** [comment]
> When you install Windows 11 Build 26200.7628 **with Rufus** the sandbox works., even on Computers which dosn't match with Windows 11

why with Rufus it works then ?

**Comment by rebel2k** [comment]
> > When you install Windows 11 Build 26200.7628 **with Rufus** the sandbox works., even on Computers which dosn't match with Windows 11
> 
> why with Rufus it works then ?

I think this is just coincidental. Indeed, the sandbox is broken for many people, but works for a few others, which means, there's no 100% guarantee it will work or not.

**Comment by Seikilos** [comment]
I agree. We are just poking around and have not found any root cause.
I tried creating a feedback using Feedback hub, but there are already several issues reported regarding this issue. So I suppose Microsoft is aware of the problem.

**Comment by oreactko** [comment]
also,sometime I run it says "Value does not fall within the expected range."

**Comment by vladimir-kordas** [comment]
I have good news! Today, after these two updates, my sandbox started working again! I had temporarily disabled it, but after these two updates, I turned it back on, installed it, and it works fine! I'll keep my fingers crossed that it helps you too  :)

<img width="1022" height="174" alt="Image" src="https://github.com/user-attachments/assets/adf52471-9f45-4d61-942e-79360f33c13c" />

**Comment by xiaoqidun** [comment]
KB5074105 26200.7705 fix

**Comment by MountComb** [comment]
Yes it works after the updates. No need to disable/re-enable.

> I have good news! Today, after these two updates, my sandbox started working again! I had temporarily disabled it, but after these two updates, I turned it back on, installed it, and it works fine! I'll keep my fingers crossed that it helps you too :)

**Comment by buchizo** [comment]
Good news
https://support.microsoft.com/en-us/topic/january-29-2026-kb5074105-os-builds-26200-7705-and-26100-7705-preview-85bd25de-894a-43eb-a19b-9a59d10f194b

> [Windows Sandbox] Fixed: This update addresses an issue that could cause Windows Sandbox to stop responding during start up and display error 0x800705b4.

**Comment by Seikilos** [comment]
> Good news https://support.microsoft.com/en-us/topic/january-29-2026-kb5074105-os-builds-26200-7705-and-26100-7705-preview-85bd25de-894a-43eb-a19b-9a59d10f194b
> 
> > [Windows Sandbox] Fixed: This update addresses an issue that could cause Windows Sandbox to stop responding during start up and display error 0x800705b4.

Except for the curious engineer. I really would love to know what caused it and how it was fixed!

**Comment by rebel2k** [comment]
It looks like the contact I had really helped to get some attention to it!!!! So nice it's working again. Hope it's not going to be broken by the next update! Well done everyone, for having commented here and helped figure it out!

**Comment by jv902337** [comment]
Still failing for me initially had the timeout. I removed and re added twice and still fails but this time it won't initialize

Windows Sandbox failed to initialize.
The virtual machine or container exited unexpectedly. (0x80370106)

I did quite a bit of testing that could have caused another issue. I'll post again if I get it working

**Comment by rebel2k** [comment]
It looks like the contact I had a couple of days ago with Microsoft really helped!!! Thank you very much to all of you for having shared your feedback here and having helped to investigate and contributed to the visibility so we could get attention and have this fixed! :)

**Comment by Seikilos** [comment]
Worth noting that KB5074105 seems to be a preview update. I don't know whether non Windows-Insider users get this update rolled out at this time.

**Comment by chocmake** [comment]
> Worth noting that KB5074105 seems to be a preview update. I don't know whether non Windows-Insider users get this update rolled out at this time.

I'm not on an Insider build (nor do I have 'Get the latest updates as soon as they're available' enabled) but it showed up as a preview update banner in the Update settings. Confirmed it resolved the launch issue on my 24H2 install.

**Comment by BartRennes** [comment]
I confirm the fix with the update 5074105 :)

**Comment by Rhadamantyszeroz** [comment]
Yes finally with this updates sandbox start to run again :)

**Comment by calimegot** [comment]
KB5074105 wont solve the problem for me... still stuck ... 
WSL, WSA, Sandbox are KO
but now, there 's a message on the box "you are disconnected... do you want to reconnect" ...

**Comment by calimegot** [comment]
<img width="1400" height="856" alt="Image" src="https://github.com/user-attachments/assets/fd077b27-eb66-4240-8654-c2162310771a" />

**Comment by calimegot** [comment]
OK, i found the solution
i must disable the vGPU 

gpedit.msc : and deactivate vGPU in this section
:-)

<img width="1213" height="970" alt="Image" src="https://github.com/user-attachments/assets/5fe96228-9d8e-42a8-ad18-710d09a5d7bd" />

**Comment by calimegot** [comment]
Problem persist for Linux Distro and WSA (android applications)

**Comment by rebel2k** [comment]
> Problem persist for Linux Distro and WSA (android applications)

Did you try to uninstall Sandbox and reinstall it? Are your graphic card drivers up to date? It's now something else which is a different issue than the original bug affecting you...

**Comment by calimegot** [comment]
> > Problem persist for Linux Distro and WSA (android applications)
> 
> Did you try to uninstall Sandbox and reinstall it? Are your graphic card drivers up to date? It's now something else which is a different issue than the original bug affecting you...

Yes of course. i made an uninstall / install of WSA / WSL subsystem.
Actually i solved the problem for SANDBOX with vGPU deactivated
But with 24H2, i could use some Android applications, now i can't. since the last 25H2 version 26200.7705, (normal canal ! i'm not insider on this computer)

**Comment by x8009** [comment]
is.the update causing any other issues ? does the dGPU works now in chrome there ?

**Comment by rcutanda** [comment]
> Good news https://support.microsoft.com/en-us/topic/january-29-2026-kb5074105-os-builds-26200-7705-and-26100-7705-preview-85bd25de-894a-43eb-a19b-9a59d10f194b
> 
> > [Windows Sandbox] Fixed: This update addresses an issue that could cause Windows Sandbox to stop responding during start up and display error 0x800705b4.

Finally! The update fixed Sandbox for me too.

**Comment by LentoMan** [comment]
> is.the update causing any other issues ? does the dGPU works now in chrome there ?

Some Chromium based games using NW.js, for example RPG Maker games, appears to take a long time to start and is lacking sound. Grabbing the latest NW.js runtime, extracting it into the game folder and then starting with nw.exe appears to fix both issues though.

**Comment by CirrusBin** [comment]
I confirm, Windows Sandbox is fixed with update KB5074105.

**Comment by dcavni** [comment]
Fixed for me too.

**Comment by Necr0man** [comment]
Also confirmed, finally KB5074105 fixed Windows Sandbox!! I missed it 😄
https://support.microsoft.com/en-us/topic/january-29-2026-kb5074105-os-builds-26200-7705-and-26100-7705-preview-85bd25de-894a-43eb-a19b-9a59d10f194b

**Comment by pomme-poire** [comment]
KB5074105 also fixed my issue on Win 11 24H2 Pro
it wasn't available in my Windows Update so I downloaded it from here
https://www.catalog.update.microsoft.com/Search.aspx?q=KB5074105

**Comment by linghengqian** [comment]
It appears that KB5074105 is starting to be rolled out in Windows updates on a large scale.

<img width="1404" height="1404" alt="Image" src="https://github.com/user-attachments/assets/6e1de41d-c6db-458d-88aa-2edad8fb6752" />

**Comment by x8009** [comment]
I wouldn't update this. It has so many issues in games . for example forza horizon 5 with nvidia.  and a friend had his explorer freeze for 2-3 min after booting every restart. uninstalling fix both issues, even nvidia says that about the update.
Sandbox can wait.

**Comment by rebel2k** [comment]
I have no issue with games on my side... Weird... Could you please share where Nvidia is stating there are issues?

**Comment by x8009** [comment]
https://forums.guru3d.com/threads/nvidia-geforce-591-86-whql-driver.459198/page-11

<img width="1222" height="508" alt="Image" src="https://github.com/user-attachments/assets/b45e478b-9717-4fab-9762-50d22ccc72b0" />

**Comment by Roshangone** [comment]
> > Good news https://support.microsoft.com/en-us/topic/january-29-2026-kb5074105-os-builds-26200-7705-and-26100-7705-preview-85bd25de-894a-43eb-a19b-9a59d10f194b
> > > [Windows Sandbox] Fixed: This update addresses an issue that could cause Windows Sandbox to stop responding during start up and display error 0x800705b4.
> 
> Finally! The update fixed Sandbox for me too.

KB5074105 Update has fixed my issue too, Able to access the sandbox now, But not sure on game issues.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/c5bedc71-c1b1-4b76-92ea-e05b613a08a6" />

**Comment by wzj-zz** [comment]
<img width="686" height="580" alt="Image" src="https://github.com/user-attachments/assets/5e7a5210-5e42-4727-b62c-12d97c08d343" />


Microsoft Windows [Version 10.0.26220.7752]   still has issues.

**Comment by ackh** [comment]
The Windows update 2026-02 Security Update (KB5077181) (26200.7840) fixed this for me.

**Comment by maxbox68** [comment]
Windows Sandbox version
0.5.3

Windows build number
10.0.26300.7939

I've tried every possible solution I found on the web, but there's nothing to do!

Sanbox starts, and after a few seconds I get the error:

"Windows Sandbox failed to initialize.

The system cannot find the file specified. (0x80070002)"

Any help?

Or should I wait for a new update?

**Comment by CompactProducer** [comment]
> Windows Sandbox version 0.5.3
> 
> Windows build number 10.0.26300.7939
> 
> I've tried every possible solution I found on the web, but there's nothing to do!
> 
> Sanbox starts, and after a few seconds I get the error:
> 
> "Windows Sandbox failed to initialize.
> 
> The system cannot find the file specified. (0x80070002)"
> 
> Any help?
> 
> Or should I wait for a new update?

Try disabling and re-enabling Windows Sandbox from the Windows Features dialog box in Control Panel.

**Comment by rolandambrosi** [comment]
> > Windows Sandbox version 0.5.3
> > Windows build number 10.0.26300.7939
> > I've tried every possible solution I found on the web, but there's nothing to do!
> > Sanbox starts, and after a few seconds I get the error:
> > "Windows Sandbox failed to initialize.
> > The system cannot find the file specified. (0x80070002)"
> > Any help?
> > Or should I wait for a new update?
> 
> Try disabling and re-enabling Windows Sandbox from the Windows Features dialog box in Control Panel.

I've had the same error. In my case the solution was de- and reinstall Microsoft Edge. No idea why but it fix the error.

**Comment by maxbox68** [comment]
@CompactProducer :
> > Windows Sandbox version 0.5.3
> 
> Try disabling and re-enabling Windows Sandbox from the Windows Features dialog box in Control Panel.

don't work ! already tried !

> > > Windows Sandbox version 0.5.3

@rolandambrosi > > 
> > Try disabling and re-enabling Windows Sandbox from the Windows Features dialog box in Control Panel.
> 
> I've had the same error. In my case the solution was de- and reinstall Microsoft Edge. No idea why but it fix the error.

don't work ! already tried !

solution was wait the next new windows version!!
now i'm in buil 26300.8068 and windws sandbox works like a charm !
I think this is a new version, some new grafical differencies and new menu differencies, but system say me always 0.5.3 version !

**Comment by sunnywu484** [comment]
My Sandbox was working a few hours ago until Windows Update installed 2026-03 Security Update (KB5079473) (26200.8037). Now it just spins and spins, and then throws a "The connection to the Windows Sandbox environment was lost. Do you want to reconnect?" Already tried disabling it and reenabling it in the Optional Features settings, with no luck.

**Comment by calimegot** [comment]
@maxbox68 
Try this... 
gpedit.msc , and : 
<img width="1213" height="970" alt="Image" src="https://github.com/user-attachments/assets/8970240b-d086-4c8c-815a-3c553483191e" />

**Comment by rklec** [comment]
Same issue. Windows 11 25H2 (Build 26200.8037)
It used to work.

<img width="759" height="392" alt="Image" src="https://github.com/user-attachments/assets/3fda4d22-2ddd-4e24-b128-9afe77bf76f2" />

Which translates roughly to:
> Error initialising Windows Sandbox.
>
>Logon failed: The user does not have the required logon type on this computer. (0x80070569)

**Comment by rklec** [comment]
@calimegot The [option to enable or disable vGPU](https://www.elevenforum.com/t/enable-or-disable-vgpu-sharing-for-windows-sandbox-in-windows-11.10235/) does not seem to make a difference here. [This article suggests rejoining the AD group](https://www.thewindowsclub.com/windows-sandbox-failed-to-start-error-0x80070569) but this is really not something you "just want to do lightly".

**Comment by Tender-song** [comment]
I am using Windows 10 and encountered the 0x800705B4 error when launching Windows Sandbox.

Before finding the solution, I tried various troubleshooting steps, including but not limited to:

- Disabling vGPU in configuration files.

- Adjusting network adapters and HNS settings.

- Re-installing the Windows Sandbox feature.

- Toggling related services and disabling antivirus software.

None of the above worked. Ultimately, updating the NVIDIA graphics driver to the latest version(596.21) and rebooting the device resolved the issue, and the Sandbox now starts normally.

I highly recommend upgrading your graphics drivers to the latest version first when troubleshooting this specific error.

**Comment by jbachiller-sud0** [comment]
After multiple attempts to uninstall, reinstall, repair, and reset Windows Sandbox and other system components on Windows 11 (Build 10.0.26200 / 25H2)—including repairing the OS itself and uninstalling/reinstalling several Windows updates—I was finally able to pinpoint the root cause.

In my case, the issue was **graphics driver–related**.

Initially, I updated my discrete GPU drivers, but that alone did not resolve the problem. I was running an AMD Radeon card, and even with the latest drivers installed, Windows Sandbox continued to fail with the Reconnect issue. I rolled back all AMD drivers, ran the AMD Cleanup Utility, and saw temporary improvement, but the problem eventually returned.

What ultimately resolved it was disabling the onboard graphics adapter. After disabling the Intel UHD Graphics 770 driver in Device Manager, Windows Sandbox began launching normally and consistently. I then reinstalled the latest AMD drivers—specifically the OEM drivers from the Dell support site, not the AMD Adrenaline Suite—and the system has remained stable since.

**TLDR: Before repairing or resetting Windows Sandbox or other system components, try disabling the onboard graphics adapter in Device Manager. This alone resolved the issue for me without requiring further OS-level repairs.**

<img width="732" height="965" alt="Image" src="https://github.com/user-attachments/assets/448d912c-b0d0-4b81-8c8e-95353c13524d" />
