### ISSUE TITLE
[Bug]: Get-CimInstance win32_ComputerSystem fails with PermissionDenied (0x80070005)

### ISSUE THREAD

**Issue by lostmsu** [microsoft/Windows-Sandbox-Utilities#67]
### Windows Sandbox version

0.4.30

### Windows build number

10.0.26100.0

### Steps to reproduce the bug

1. Open PowerShell
2. Enter command `Get-CimInstance win32_ComputerSystem`

### Expected result

should not fail

### Actual result

Get-CimInstance: Access is denied.

**Comment by asheroto** [comment]
Also seeing this.

![Image](https://github.com/user-attachments/assets/b251e89e-a075-41ad-b515-99db55bc4f5a)

**Comment by asheroto** [comment]
@kvega005, this was marked as completed, is it fixed in a later version?

**Comment by krehberger** [comment]
After installation of KB5058499 the error is still there! 

![Image](https://github.com/user-attachments/assets/cadbbae1-3dc5-4d83-85b9-731524f26515)
